name: Feature request
description: An idea to make Django ORM Lens more useful
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations: { required: true }
  - type: textarea
    id: idea
    attributes:
      label: Proposed solution
    validations: { required: true }
  - type: textarea
    id: alt
    attributes:
      label: Alternatives you considered
